Ability to configure addon provisioning timeout
heroku/terraform-provider-heroku pull request #292
Opened 2020-12-02 23:34 UTC by davidji99

2020-12-03 22:30 UTC, mars requested changes
Looks good, except the test failures.

2020-12-03 22:30 UTC, mars commented on heroku/resource_heroku_addon.go
> +	// This should be only set after the addon provisioning has been fully completed.
Failures in CI tests:

```
=== RUN   TestAccDatasourceHerokuAddon_Basic
Error:     testing.go:684: Step 0 error: errors during apply:
        Error: Error waiting for Addon () to be provisioned: timeout while waiting for state to become 'provisioned'
```

Looks like this change caused the above usage of `d.Id()` to become invalid, the retrier has no ID.

2020-12-14 02:11 UTC, davidji99 commented on heroku/resource_heroku_addon.go
> +	// This should be only set after the addon provisioning has been fully completed.
Ah! Oops!

2020-12-14 18:27 UTC, mars commented on heroku/resource_heroku_addon.go
> +	log.Printf("[INFO] Addon ID: %s", d.Id())
This seems to be logging the wrong ID, should it be `a.Id()`.

2020-12-14 22:24 UTC, davidji99 commented on heroku/resource_heroku_addon.go
> +	log.Printf("[INFO] Addon ID: %s", d.Id())
That's okay because in L144, we set the resource `d` to `a.ID`.

2020-12-14 22:25 UTC, mars commented on heroku/resource_heroku_addon.go
> +	log.Printf("[INFO] Addon ID: %s", d.Id())
👌  I see, looks good @davidji99 .

2020-12-14 22:26 UTC, mars approved these changes

2020-12-14 22:29 UTC, davidji99 commented on heroku/resource_heroku_addon.go
> +	log.Printf("[INFO] Addon ID: %s", d.Id())
THanks!

2020-12-14 22:30 UTC, merged