Update provider docs to use new directory format
heroku/terraform-provider-heroku pull request #298
Opened 2021-03-02 07:16 UTC by davidji99

New docs directory moves from `website/` to `docs/`. Filenames drop the `.html.markdown` reference and just use `.md`.

Additionally, I'm updating the doc themselves by checking for any syntax changes, broken links, etc.

2021-03-02 16:40 UTC, bernerdschaefer approved these changes
Oh, wonderful! I mostly skimmed, so let me know if there are any specific changes you want extra eyes on. Otherwise looks good to me! :shipit:

2021-03-02 17:08 UTC, mars requested changes
Nice improvements in addition to the fundamental directory fix 🙌😄

2021-03-02 17:08 UTC, mars commented on README.md
>    version = "~> 2.0"
This example version should probably updated for the current major version.

2021-03-02 17:08 UTC, mars commented on docs/resources/app.md
> +
These line-breaks between Markdown bullet list items actually makes every item a separate list.

Please remove these added inter-item line breaks.

2021-03-02 17:08 UTC, mars commented on docs/resources/formation.md
> +Please note the following:
Thank you for fixing these Hashicorp-specific style anomalies!

2021-03-02 23:48 UTC, davidji99 commented on README.md
>    version = "~> 2.0"
Done.

2021-03-02 23:55 UTC, davidji99 commented on docs/resources/app.md
> +
Changed.

2021-03-03 00:07 UTC, mars approved these changes

2021-03-03 02:33 UTC, merged