New resource: heroku_review_app_config
heroku/terraform-provider-heroku pull request #303
Opened 2021-04-05 03:38 UTC by davidji99

2021-04-14 17:58 UTC, mars requested changes
Fantastic new feature 🎆The implementation looks great 👍

My requested changes are all to make the documentation & examples more user-friendly.

2021-04-14 17:58 UTC, mars commented on docs/resources/review_app_config.md
> +// Enable Github integration and connect pipeline to a Github repository.
This comment seems confusing to people who may not understand this manual process already (including myself 🤷).

Can these example resources actually exist in the Terraform configuration together, and not result in `terraform apply` failing, or needing to be re-run once the repo is manually connected?

Here's a suggestion to make this clearer; please revise to make it more correct 🙏 

```suggestion
// Once the pipeline is created, manually connect it to a GitHub repo using the Heroku Dashboard.
// Run `terraform apply` again after manually configuring, in order to complete setup.
```

2021-04-14 17:58 UTC, mars commented on heroku/resource_heroku_review_app_config.go
> +func resourceHerokuReviewAppConfigCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
`diag.Diagnostics` 👀 nice new SDK feature! (found [this describing usage](https://www.terraform.io/docs/extend/guides/v2-upgrade-guide.html#support-for-diagnostics))

2021-04-14 17:58 UTC, mars commented on heroku/resource_heroku_review_app_config_test.go
> +// to reference an existing pre-configured pipeline is the optimal route to test review apps configs.
This would be useful information for the user-facing documentation, since the example config seems to suggest that `heroku_pipeline` & `heroku_review_app_config` can coexist in a configuration.

2021-04-14 17:58 UTC, mars commented on docs/resources/review_app_config.md
> +resource "heroku_pipeline" "test-pipeline" {
Could this be a `data` source instead? (As referenced in my testing comment.)

Ideally the configuration examples are copy-paste friendly.

2021-04-15 04:32 UTC, davidji99 commented on docs/resources/review_app_config.md
> +// Enable Github integration and connect pipeline to a Github repository.
Yeah, I can clarify things here.

2021-04-15 04:32 UTC, davidji99 commented on docs/resources/review_app_config.md
> +resource "heroku_pipeline" "test-pipeline" {
Yeah, I can clarify things here.

2021-04-15 18:39 UTC, mars approved these changes
Looks great @davidji99 👏  just on more test doc suggestion before calling it done!

2021-04-15 22:08 UTC, davidji99 commented on helper/test/config.go
> +	TestConfigPipelineID:           "HEROKU_PIPELINE_ID",
Ah I thought I added that. Will do!

2021-04-16 01:42 UTC, merged